In [1]:
import numpy as np

lista=[2,1,3,4] #a list
np.array(lista) #now an array


array([2, 1, 3, 4])

In [5]:
a=np.zeros((2,4)) #an array of zero

a


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b=np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
c = np.linspace(2,4) #an array of linearly spaced values
c

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [12]:
d=np.arange(10).reshape(2,5) #arrange 100values in the shape of 2x5
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
a+b #add

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
a * b #multiplication

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
a/b #divide  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.log10(12.8) #log value

1.1072099696478683

In [25]:
np.sin(a) #sin of a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
e = np.arange(12)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
e.reshape(3,-1) #5rows x arbitrary columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
#Indexing
print(e)
e[0:3] #start at 0 and end at 2 but exclude 3

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([0, 1, 2])

In [32]:
e[:5:2] #start end step

array([0, 2, 4])

In [34]:
b=np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
with open("mytext.txt", "w") as f:   #with key word before open is to ensure we dont leave the file open
    f.write("Numpy is amazing")